fix use of dma mapped buffer for usb bulk transfer
aurorafossorg/rts5139 pull request #1
Opened 2023-09-01 18:33 UTC by citronalco

Fix following error with Linux >= 5.18:
hci_hcd 0000:00:14.0: rejecting DMA map of vmalloc memory WARNING: CPU: 3 PID: 6104 at include/linux/dma-mapping.h:331 usb_hcd_map_urb_for_dma+0x3de/0x480 [usbcore]

Honestly I don't know exactly what I'm doing here, but the newer driver rtsx_usb had the same issue, and it got fixes by Shuah Khan in a similar way: https://lore.kernel.org/all/667d627d502e1ba9ff4f9b94966df3299d2d3c0d.1656642167.git.skhan@linuxfoundation.org/

2023-09-07 15:06 UTC, ljmf00 requested changes

2023-09-07 15:06 UTC, ljmf00 commented on rts51x.h
> +	return kmalloc(size, mem_flags);
Please use macro to select the correct linux version header.

2023-09-07 19:43 UTC, citronalco commented
OK, done.

2023-09-09 23:00 UTC, ljmf00 approved these changes

2023-09-09 23:01 UTC, ljmf00 commented
Going to merge/rebase when I'm home. Feel free to ping me if I end up forgetting 🤭☺️

2023-09-21 13:38 UTC, citronalco commented
Ping!

2023-09-24 03:15 UTC, merged